In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.tree import DecisionTreeClassifier

In [4]:
df= pd.read_csv('diabetes.csv')

In [5]:
df.head()

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [8]:
df.drop(columns=['AnyHealthcare','NoDocbcCost','CholCheck','Education','Income'],inplace= True)

In [11]:
X_train,X_test,y_train,y_test= train_test_split(df.drop(columns= ['Diabetes_012']),df['Diabetes_012'],test_size=0.2,random_state=42)

In [12]:
X_train.head()

,HighBP,HighChol,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age
31141,0.0,1.0,20.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,2.0,0.0,0.0,0.0,1.0,12.0
98230,0.0,0.0,34.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,8.0
89662,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,2.0,0.0,5.0,0.0,1.0,12.0
208255,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0
233415,0.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,3.0,0.0,0.0,1.0,0.0,12.0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 17 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Diabetes_012          253680 non-null  float64
 1   HighBP                253680 non-null  float64
 2   HighChol              253680 non-null  float64
 3   BMI                   253680 non-null  float64
 4   Smoker                253680 non-null  float64
 5   Stroke                253680 non-null  float64
 6   HeartDiseaseorAttack  253680 non-null  float64
 7   PhysActivity          253680 non-null  float64
 8   Fruits                253680 non-null  float64
 9   Veggies               253680 non-null  float64
 10  HvyAlcoholConsump     253680 non-null  float64
 11  GenHlth               253680 non-null  float64
 12  MentHlth              253680 non-null  float64
 13  PhysHlth              253680 non-null  float64
 14  DiffWalk              253680 non-null  float64
 15  Sex                   253680 non-null  float64
 16  Age                   253680 non-null  float64
dtypes: float64(17)
memory usage: 32.9 MB

In [14]:
y_train.sample(5)

169087    0.0
241678    0.0
109362    0.0
110187    0.0
191896    0.0
Name: Diabetes_012, dtype: float64

In [15]:
df.isnull().sum()

Diabetes_012            0
HighBP                  0
HighChol                0
BMI                     0
Smoker                  0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
dtype: int64

In [16]:
#scaling
#min max because using feature engineering.
trf1= ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,16))
])

In [17]:
trf2= SelectKBest(score_func= chi2,k=8)

In [18]:
trf3 = DecisionTreeClassifier()

In [20]:
pipe = Pipeline([
    ('trf1',trf1),
    ('trf2',trf2),
    ('trf3',trf3)
])

In [23]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 16, None))])),
                ('trf2',
                 SelectKBest(k=8,
                             score_func=<function chi2 at 0x000002404CD62D40>)),
                ('trf3', DecisionTreeClassifier())])

In [22]:
from sklearn import set_config
set_config(display ='diagram')

In [24]:
y_pred = pipe.predict(X_test)

In [26]:
y_pred

array([0., 0., 0., ..., 0., 0., 0.], shape=(50736,))

In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8393842636392306

In [28]:
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X_train,y_train,cv=5, scoring='accuracy').mean()

np.float64(0.8356295285924809)

In [30]:
params ={
    'trf3__max_depth':[1,2,3,4,5,None]
}

In [32]:
import pickle
pickle.dump(pipe,open('diabetesP.pkl','wb'))